Feature/step4
kakao-ent-2022/w3-simple-page pull request #4
Opened 2022-01-24 17:26 UTC by river-o

2022-01-27 09:15 UTC, bamiboo requested changes

2022-01-27 09:15 UTC, bamiboo-han commented on PageApp/PageApp/content/ContentViewController.swift
> +}
enum 은 주로 case 에 따라 분기를 하기위해 사용합니다~
class 보다 가볍게 구현하고 싶으셨다면 struct 를 활용해보시면 좋겠습니다!

그리고 static 로 선언될 경우 앱이 실행되는 내내 메모리에서 release 되지않고 유지되기 때문에
다양한 클래스 내에서 활용될 변수가 아니라면 최대한 지양하는것이 좋습니다!

https://seons-dev.tistory.com/30 참고해보세요~~

2022-01-28 02:06 UTC, river-o commented on PageApp/PageApp/content/ContentViewController.swift
> +}
상수를 한곳에 모아 관리하고 싶어서 다음과 같은 방식을 썼는데 확실히 보내주신 링크를 읽어보니 enum보다는 struct가 좋다는 생각이 들었습니다! struct로 변경했습니다!~

또한, 말씀해주신 대로 static을 무분별하게 쓴 감이 있어서 여러 클래스에서 활용되는 변수만 제외하고 클래스 내부에 let으로 선언하여 instance 변수로 변경해주었습니다! 

피드백 감사합니다!! :) 
55f8914

2022-01-28 02:49 UTC, bamiboo approved these changes

2022-01-28 05:42 UTC, kyoo-sl approved these changes
확인했습니다~

2022-02-03 01:52 UTC, merged